import crypto from 'node:crypto';
import fs from 'node:fs';

const read = file => fs.readFileSync(file, 'utf8');
const version = JSON.parse(read('version.json'));
const site = read('index.html');
const siteCss = read('assets/site.css');
const siteJs = read('assets/site.js');
const app = read('app/index.html');
const appCss = read('app/app.css');
const appJs = read('app/app.js');
const appVersion = JSON.parse(read('app/version.json'));
const workflow = read('.github/workflows/deploy-pages.yml');
const mainActivity = read('android/app/src/main/java/ca/skymapontario/app/MainActivity.java');
const geoMetProxy = read('android/app/src/main/java/ca/skymapontario/app/GeoMetProxy.java');
const refreshWorker = read('android/app/src/main/java/ca/skymapontario/app/WeatherRefreshWorker.java');
const bridge = read('android/app/src/main/java/ca/skymapontario/app/SkyMapBridge.java');
const updateWorker = read('android/app/src/main/java/ca/skymapontario/app/UpdateCheckWorker.java');
const updateManager = read('android/app/src/main/java/ca/skymapontario/app/UpdateManager.java');
const application = read('android/app/src/main/java/ca/skymapontario/app/SkyMapApplication.java');
const buildGradle = read('android/app/build.gradle');
const proguard = read('android/app/proguard-rules.pro');
const signingGuide = read('docs/RELEASE_SIGNING.md');
const androidManifest = read('android/app/src/main/AndroidManifest.xml');
const updatePaths = read('android/app/src/main/res/xml/update_file_paths.xml');
const publicKey = fs.readFileSync('android/app/signing/skymap-public-release.jks');

const assert = (condition, message) => { if (!condition) throw new Error(message); };
assert(/^\d+\.\d+\.\d+$/.test(version.version), 'Version must use semantic versioning');
assert(Number.isInteger(version.versionCode), 'versionCode must be an integer');
assert(appVersion.version === version.version && appVersion.versionCode === version.versionCode, 'Web app version is not aligned');
assert(appJs.includes(`version: '${version.version}'`), 'Web app fallback version is not aligned');
assert(site.includes('Weather,<br><em>moving toward you.</em>'), 'Radar-first hero is missing');
assert(!site.includes('<iframe'), 'Landing page must not embed the full app');
assert((site.match(/ko-fi\.com\/rbt4dev/g) || []).length >= 3, 'Ko-fi support must remain visible');
assert(site.includes('data-apk'), 'Public APK link is missing');
assert(siteCss.length < 30000, 'Landing CSS has become bloated');
assert(siteJs.length < 6000, 'Landing JavaScript has become bloated');
assert(app.includes('WEATHER SNAPSHOTS'), 'Snapshot rail is missing');
assert(app.includes('7-DAY FORECAST'), 'Seven-day forecast is missing');
assert(app.includes('Keep radar first'), 'Layer sheet is missing its radar-first hierarchy');
assert(app.includes('id="story-facts"'), 'Selected-time explanation facts are missing');
assert(app.includes('id="zoom-in-button"') && app.includes('id="zoom-out-button"'), 'Visible map zoom controls are missing');
assert(app.includes('ko-fi.com/rbt4dev'), 'Restrained in-app support link is missing');
assert(appCss.includes('grid-template-columns:minmax(0,1.45fr)'), 'Desktop map/forecast layout is missing');
assert(appCss.includes('@media(max-width:980px)'), 'Mobile layout is missing');
assert(appJs.includes('NATIVE_GEOMET'), 'Native GeoMet relay is missing');
assert(appJs.includes('Promise.allSettled'), 'Progressive source loading is missing');
assert(appJs.includes('buildSnapshots'), 'Meaningful snapshots are missing');
assert(appJs.includes('buildDaily'), 'Daily forecast generation is missing');
assert(appJs.includes('citypageweather-realtime'), 'Official ECCC city forecast context is missing');
assert(appJs.includes("timeformat: 'unixtime'"), 'Timezone-safe model timestamps are missing');
assert(appJs.includes('modelDate(data, value)'), 'UNIX forecast timestamp parsing is missing');
assert(appJs.includes('updateFrameExplanation'), 'Per-frame radar explanation is missing');
assert(appJs.includes('function formatWmsTime'), 'Whole-second WMS timestamp formatting is missing');
assert(appJs.includes("replace(/\\.\\d{3}Z$/, 'Z')"), 'WMS timestamps may still include unsupported milliseconds');
assert(appJs.includes('Point value unavailable'), 'Failed point queries are not distinguished from zero rain');
assert(appJs.includes('fetchCompleteJson'), 'Point queries are not protected through complete response parsing');
assert(appJs.includes('pointValueRequests'), 'Duplicate point queries are not coalesced');
assert(appJs.includes("formatWmsTime(frame.referenceTime)"), 'Point-query reference times may still include unsupported milliseconds');
assert(appJs.includes('await updateFrameExplanation(frame)'), 'The selected point must resolve before arrival probing begins');
assert(appJs.includes('function frameStamp'), 'Selected radar date-and-time label is missing');
assert(appJs.includes('crossingNow ? 1650 : 1100'), 'Calm one-pass radar timing is missing');
assert(appJs.includes('RAQDPS.Sfc_PM2.5-WildfireSmokePlume'), 'Wildfire-specific smoke guidance is missing');
assert(appJs.includes('if (state.frameIndex >= state.frames.length - 1)'), 'Radar playback must stop instead of looping forever');
assert((app.match(/\sid="([^"]+)"/g) || []).length === new Set([...app.matchAll(/\sid="([^"]+)"/g)].map(match => match[1])).size, 'Duplicate app element IDs detected');
assert(!site.includes('v4.4') && !site.includes('Version 4.4'), 'Stale v4.4 copy remains');
assert(!app.includes('SkyMap Ontario 13'), 'Stale v13 app copy remains');
assert(!`${site}\n${siteJs}\n${app}\n${appJs}`.includes('wet signal'), 'Unexplained wet-signal copy remains');
assert(mainActivity.includes(`SkyMapOntario/${version.version}`), 'Android WebView version is not aligned');
assert(geoMetProxy.includes(`SkyMapOntario/${version.version}`), 'Native GeoMet relay version is not aligned');
assert(refreshWorker.includes(`SkyMapOntario/${version.version}`), 'Background refresh version is not aligned');
assert(updateWorker.includes(`SkyMapOntario/${version.version} updater`), 'Updater version is not aligned');
assert(refreshWorker.includes('&timeformat=unixtime'), 'Android background forecast timestamps are not timezone-safe');
assert(refreshWorker.includes('parseForecastTime'), 'Android background forecast timestamp parsing is missing');
assert(workflow.includes('node scripts/check-live-sources.mjs'), 'Live source validation is not wired into deployment');
assert(!workflow.includes('git push origin HEAD:main'), 'Deployment must not rewrite its own source branch');
assert(!workflow.includes('git fetch origin') && !workflow.includes('git checkout origin/'), 'Deployment must build the checked-out readable source directly');

// --- 14.2 guarantees -------------------------------------------------------
const sw = read('app/sw.js');
const tinyApp = [...appCss.matchAll(/font-size:\s*([\d.]+)px/g)].map(match => Number(match[1])).filter(size => size < 11);
assert(!tinyApp.length, `Unreadable type returned to the app: ${[...new Set(tinyApp)].join('px, ')}px`);
const tinySite = [...siteCss.matchAll(/font-size:\s*([\d.]+)px/g)].map(match => Number(match[1])).filter(size => size < 11);
assert(!tinySite.length, `Unreadable type returned to the site: ${[...new Set(tinySite)].join('px, ')}px`);
assert(app.includes('id="alert-banner"'), 'Break-through alert banner is missing');
assert(app.includes('id="alert-list"'), 'Alert detail sheet is missing');
assert(appJs.includes('function renderAlerts'), 'Alerts are fetched but never rendered');
assert(appJs.includes('expiration_datetime'), 'Expired alerts are not filtered out');
assert(app.includes('data-layer="air"'), 'Air quality view is missing');
assert(appJs.includes('aqhi-observations-realtime'), 'Official AQHI point reading is missing');
assert(app.includes('id="map-legend"'), 'The in-interface legend is missing');
assert(appJs.includes('LEGENDS'), 'Per-view legend data is missing');
assert(appJs.includes('dark_only_labels') && appJs.includes("createPane('labelPane')"), 'Place labels are no longer drawn above the weather');
assert(appJs.includes('function esc('), 'HTML escaping helper is missing');
assert(app.includes('Content-Security-Policy') && site.includes('Content-Security-Policy'), 'Content-Security-Policy is missing');
assert(sw.includes(`const VERSION = '${version.version}'`), 'Service worker version is not aligned');
assert(app.includes('serviceWorker'), 'Service worker is never registered');
assert(geoMetProxy.includes('safeHeaders') && !geoMetProxy.includes('flattenHeaders'), 'Native relay still forwards upstream headers verbatim');
assert(androidManifest.includes('android:allowBackup="false"'), 'Cached weather and saved location are still cloud-backed-up');

// --- 14.2.1 continuity and security guarantees ----------------------------
assert(version.version === '14.2.1' && version.versionCode === 14021, 'Release version is not 14.2.1 / 14021');
assert(version.releaseName === 'Continuity', 'Release name is not Continuity');
assert(buildGradle.includes("storeFile file('signing/skymap-public-release.jks')"), 'Public continuity keystore is not attached');
assert(buildGradle.includes("storePassword 'skymap-public-release'"), 'Public keystore credentials are not explicit');
assert(buildGradle.includes('signingConfig signingConfigs.release'), 'Release signing configuration is not attached');
assert(buildGradle.includes('minifyEnabled true'), 'R8 minification is not enabled for release');
assert(buildGradle.includes('debuggable false'), 'Release build is not explicitly non-debuggable');
assert(workflow.includes(':android-app:assembleRelease'), 'Workflow does not build the release APK');
assert(!workflow.includes('assembleDebug'), 'Debug APK build returned to the release workflow');
assert(workflow.includes('outputs/apk/release/android-app-release.apk'), 'Workflow does not consume the release APK path');
assert(!workflow.includes('debug.keystore') && !workflow.includes('androiddebugkey'), 'Android debug signing material returned');
assert(!workflow.includes('SKYMAP_KEYSTORE_B64') && !workflow.includes('SKYMAP_KEYSTORE_PASSWORD'), 'Secret-based signing unexpectedly returned');
assert(workflow.includes('Verify public continuity signing key'), 'Public continuity key is not verified in CI');
assert(workflow.includes('A3E872DE448550E75754DED732B94A403A5FD216B17BA0A80C9D74F4F5E4E344'), 'APK signer fingerprint is not pinned');
assert(workflow.includes("grep -q '^application-debuggable'"), 'CI does not reject debuggable APKs');
assert(crypto.createHash('sha256').update(publicKey).digest('hex') === '70fc1f50ba731049dbd623f61fbe31449838dbfa16a362c26e9b62c0d2b4c0e2', 'Committed public keystore bytes changed');

assert(!mainActivity.includes('addJavascriptInterface'), 'Unscoped addJavascriptInterface returned');
assert(mainActivity.includes('WebViewCompat.addWebMessageListener'), 'Origin-scoped WebMessage listener is missing');
assert(mainActivity.includes('Set.of(APP_ORIGIN)'), 'Native bridge origin allowlist is missing');
assert(mainActivity.includes('isMainFrame') && mainActivity.includes('isTrustedOrigin'), 'Native messages are not restricted to the trusted main frame');
assert(mainActivity.includes('removeWebMessageListener'), 'Native message listener is not removed on teardown');
assert(!bridge.includes('@JavascriptInterface') && !bridge.includes('android.webkit.JavascriptInterface'), 'Legacy JavascriptInterface annotations remain');
assert(appJs.includes('channel.postMessage') && appJs.includes('NativeBridge.call'), 'Web app does not use the asynchronous native message channel');
assert(appJs.includes("await NativeBridge.call('getCache'"), 'Native cache reads are not asynchronous');
assert(appJs.includes('Promise.allSettled(MODELS.map(readCachedModel))'), 'Native cache hydration is not awaited safely');

// Automatic public APK update flow.
assert(androidManifest.includes('android.permission.REQUEST_INSTALL_PACKAGES'), 'APK installer permission is missing');
assert(androidManifest.includes('android:name=".SkyMapApplication"'), 'Update scheduler application is missing');
assert(androidManifest.includes('androidx.core.content.FileProvider'), 'Update FileProvider is missing');
assert(updatePaths.includes('<files-path name="updates" path="updates/"'), 'Update file path is not restricted');
assert(application.includes('UpdateManager.schedule(this)'), 'Automatic update scheduling is missing');
assert(application.includes('UpdateManager.promptPendingUpdate(activity)'), 'Ready update is not prompted on app resume');
assert(updateManager.includes('PeriodicWorkRequest.Builder(UpdateCheckWorker.class, 12, TimeUnit.HOURS)'), 'Twelve-hour update schedule is missing');
assert(updateManager.includes('Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES'), 'Unknown-app installer permission flow is missing');
assert(updateManager.includes('FileProvider.getUriForFile'), 'APK is not shared through FileProvider');
assert(updateManager.includes('PackageInfo') && updateManager.includes('getLongVersionCode'), 'Installed package version lookup is missing');
assert(updateWorker.includes('UpdateManager.currentVersionCode(context)'), 'Background updater does not compare against installed package metadata');
assert(!`${updateManager}\n${updateWorker}`.includes('BuildConfig.VERSION_CODE'), 'Updater incorrectly depends on generated BuildConfig');
assert(updateWorker.includes('release.json'), 'Updater does not read the published release receipt');
assert(updateWorker.includes('SkyMap-Ontario-latest.apk'), 'Updater does not download the stable APK URL');
assert(updateWorker.includes('SkyMap-Ontario-latest.apk.sha256'), 'Updater does not fetch the published checksum');
assert(updateWorker.includes('downloadVerified') && updateWorker.includes('APK checksum mismatch'), 'Updater does not verify the APK checksum');
assert(proguard.includes('WeatherRefreshWorker') && proguard.includes('UpdateCheckWorker'), 'R8 keep rules for WorkManager are incomplete');

const actionRefs = [...workflow.matchAll(/uses:\s*([^\s#]+)/g)].map(match => match[1]);
assert(actionRefs.length >= 8, 'Expected GitHub Actions references are missing');
assert(actionRefs.every(ref => /@[0-9a-f]{40}$/.test(ref)), `Mutable GitHub Action reference found: ${actionRefs.find(ref => !/@[0-9a-f]{40}$/.test(ref)) || 'unknown'}`);
const buildJob = workflow.split('\n  deploy:')[0];
assert(!buildJob.includes('pages: write') && !buildJob.includes('id-token: write'), 'Build job still holds deployment permissions');
assert(workflow.includes("if: github.ref == 'refs/heads/main'"), 'Pages deployment is not restricted to main');
assert(workflow.includes('SkyMap-Ontario-latest.apk.sha256'), 'Public checksum is not deployed');
assert(signingGuide.includes('private signing key') && signingGuide.includes('update continuity, not publisher authenticity'), 'Public signing risk is not documented plainly');
assert(signingGuide.includes('cannot silently install'), 'Android install-confirmation limitation is not documented');
assert(!fs.existsSync('scripts/configure-release-signing.sh'), 'Obsolete private-key setup script still exists');

console.log(`SkyMap ${version.version} validation passed`);
