import fs from 'node:fs';

const read = file => fs.readFileSync(file, 'utf8');
const version = JSON.parse(read('version.json'));
const site = read('index.html');
const siteCss = read('assets/site.css');
const siteJs = read('assets/site.js');
const app = read('app/index.html');
const appCss = read('app/app.css');
const appJs = read('app/app.js');
const appVersion = JSON.parse(read('app/version.json'));
const workflow = read('.github/workflows/deploy-pages.yml');
const mainActivity = read('android/app/src/main/java/ca/skymapontario/app/MainActivity.java');
const geoMetProxy = read('android/app/src/main/java/ca/skymapontario/app/GeoMetProxy.java');
const refreshWorker = read('android/app/src/main/java/ca/skymapontario/app/WeatherRefreshWorker.java');

const assert = (condition, message) => { if (!condition) throw new Error(message); };
assert(/^\d+\.\d+\.\d+$/.test(version.version), 'Version must use semantic versioning');
assert(Number.isInteger(version.versionCode), 'versionCode must be an integer');
assert(appVersion.version === version.version && appVersion.versionCode === version.versionCode, 'Web app version is not aligned');
assert(appJs.includes(`version: '${version.version}'`), 'Web app fallback version is not aligned');
assert(site.includes('Weather,<br><em>moving toward you.</em>'), 'Radar-first hero is missing');
assert(!site.includes('<iframe'), 'Landing page must not embed the full app');
assert((site.match(/ko-fi\.com\/rbt4dev/g) || []).length >= 3, 'Ko-fi support must remain visible');
assert(site.includes('data-apk'), 'Dynamic aligned APK link is missing');
assert(siteCss.length < 30000, 'Landing CSS has become bloated');
assert(siteJs.length < 6000, 'Landing JavaScript has become bloated');
assert(app.includes('WEATHER SNAPSHOTS'), 'Snapshot rail is missing');
assert(app.includes('7-DAY FORECAST'), 'Seven-day forecast is missing');
assert(app.includes('Keep radar first'), 'Layer sheet is missing its radar-first hierarchy');
assert(app.includes('id="story-facts"'), 'Selected-time explanation facts are missing');
assert(app.includes('id="zoom-in-button"') && app.includes('id="zoom-out-button"'), 'Visible map zoom controls are missing');
assert(app.includes('ko-fi.com/rbt4dev'), 'Restrained in-app support link is missing');
assert(appCss.includes('grid-template-columns:minmax(0,1.45fr)'), 'Desktop map/forecast layout is missing');
assert(appCss.includes('@media(max-width:980px)'), 'Mobile layout is missing');
assert(appJs.includes('NATIVE_GEOMET'), 'Native GeoMet relay is missing');
assert(appJs.includes('Promise.allSettled'), 'Progressive source loading is missing');
assert(appJs.includes('buildSnapshots'), 'Meaningful snapshots are missing');
assert(appJs.includes('buildDaily'), 'Daily forecast generation is missing');
assert(appJs.includes('citypageweather-realtime'), 'Official ECCC city forecast context is missing');
assert(appJs.includes("timeformat: 'unixtime'"), 'Timezone-safe model timestamps are missing');
assert(appJs.includes('modelDate(data, value)'), 'UNIX forecast timestamp parsing is missing');
assert(appJs.includes('updateFrameExplanation'), 'Per-frame radar explanation is missing');
assert(appJs.includes('function formatWmsTime'), 'Whole-second WMS timestamp formatting is missing');
assert(appJs.includes("replace(/\\.\\d{3}Z$/, 'Z')"), 'WMS timestamps may still include unsupported milliseconds');
assert(appJs.includes('Point value unavailable'), 'Failed point queries are not distinguished from zero rain');
assert(appJs.includes('function frameStamp'), 'Selected radar date-and-time label is missing');
assert(appJs.includes('crossingNow ? 1650 : 1100'), 'Calm one-pass radar timing is missing');
assert(appJs.includes('RAQDPS.Sfc_PM2.5-WildfireSmokePlume'), 'Wildfire-specific smoke guidance is missing');
assert(appJs.includes('if (state.frameIndex >= state.frames.length - 1)'), 'Radar playback must stop instead of looping forever');
assert((app.match(/\sid="([^"]+)"/g) || []).length === new Set([...app.matchAll(/\sid="([^"]+)"/g)].map(match => match[1])).size, 'Duplicate app element IDs detected');
assert(!site.includes('v4.4') && !site.includes('Version 4.4'), 'Stale v4.4 copy remains');
assert(!app.includes('SkyMap Ontario 13'), 'Stale v13 app copy remains');
assert(!`${site}\n${siteJs}\n${app}\n${appJs}`.includes('wet signal'), 'Unexplained wet-signal copy remains');
assert(mainActivity.includes(`SkyMapOntario/${version.version}`), 'Android WebView version is not aligned');
assert(geoMetProxy.includes(`SkyMapOntario/${version.version}`), 'Native GeoMet relay version is not aligned');
assert(refreshWorker.includes(`SkyMapOntario/${version.version}`), 'Background refresh version is not aligned');
assert(refreshWorker.includes('&timeformat=unixtime'), 'Android background forecast timestamps are not timezone-safe');
assert(refreshWorker.includes('parseForecastTime'), 'Android background forecast timestamp parsing is missing');
assert(workflow.includes('node scripts/check-live-sources.mjs'), 'Live source validation is not wired into deployment');
assert(!workflow.includes('git push origin HEAD:main'), 'Deployment must not rewrite its own source branch');
assert(!workflow.includes('git fetch origin') && !workflow.includes('git checkout origin/'), 'Deployment must build the checked-out readable source directly');
console.log(`SkyMap ${version.version} validation passed`);
